name = "FastRef"
uuid = "a50d8279-6ba1-490a-be15-b05a23539f43"
authors = ["Cloud Johnson"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
